### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by junke365** [stringsync/stringsync#93]
Is there a separate library, which is the staff interaction direction, the event library, and examples of oSMD combined.

**Comment by jaredjj3** [comment]
Thanks for reaching out. There isn't unfortunately. However, I could point you to the code that wires everything together:

- extended OSMD behavior is in: https://github.com/stringsync/stringsync/tree/master/web/src/lib/MusicDisplay
- rendering the music sheet using React is in: https://github.com/stringsync/stringsync/blob/jj/web/src/components/MusicSheet.tsx (this is a non-master branch)
- making the OSMD react to events is done in: https://github.com/stringsync/stringsync/blob/jj/web/src/components/NotationSink.tsx (this is a non-master branch)

Take a look at those and let me know if those answer your questions.

**Comment by junke365** [comment]
thank you，Can piano staff be used in this way

**Comment by jaredjj3** [comment]
Would you elaborate? Are you looking to do something like [this](https://www.instagram.com/p/BfEGY66hFBt/)?

**Comment by junke365** [comment]
Similar to the musescore,staff

**Comment by junke365** [comment]
![image](https://user-images.githubusercontent.com/25856057/180244587-b717cab1-9374-4a9a-9e4f-5f5b520d8a54.png)

**Comment by jaredjj3** [comment]
Hmm... I'm not familiar with that.  But if you're asking if you can sync piano music with stringsync, you can.

**Comment by junke365** [comment]
多谢你的答复。

**Comment by jaredjj3** [comment]
You're welcome, I'm closing this but feel free to follow up.
