### ISSUE TITLE
bosses

### ISSUE THREAD

**Issue by junke365** [stringsync/stringsync#95]
(async () => {
  
  await osmd.load('http://192.168.1.144:1337/resources/1.xml');

  const svg = osmd.imd.Drawer.Backends[0].getSvgElement();

  console.log(svg);
  const eventBus = new opensheetmusicdisplay.EventBus();
  const locator = new opensheetmusicdisplay.MusicDisplayLocator();
  const svgEventProxy = new opensheetmusicdisplay.SVGEventProxy(svg, osmd, locator,opensheetmusicdisplay.createPointerService,osmd.imd.svgSettings );
 svgEventProxy.install(svg,osmd ,osmd.imd.svgSettings);

  eventBus.subscribe('drag', (payload) => {
    console.log(`the dragged object is: ${payload.draggedObject}`);
  });
})();

![image](https://user-images.githubusercontent.com/25856057/180366395-f16855ae-a8da-4afd-8fd6-fac8300638f4.png)

![image](https://user-images.githubusercontent.com/25856057/180366426-e3e181e4-752f-4dc3-89c4-73f400235c80.png)

Hey, big guy, how does this work

**Comment by jaredjj3** [comment]
The `MusicDisplayLocator`'s purpose is to translate:

- a `timeMs` to `LocateResult`
- an `x` and `y` to `LocateResult`

This is a performance-sensitive part of the system. The class employs two different search algorithms for each input, including binary search (which is considered the expensive route).

You're running into an error because you created a `MusicDisplayLocator` using `new` instead of the factory method `MusicDisplayLocator.create`. Take a look at: https://github.com/stringsync/stringsync/blob/master/web/src/lib/MusicDisplay/locator/MusicDisplayLocator.ts

**Comment by junke365** [comment]
![image](https://user-images.githubusercontent.com/25856057/180435637-1a0144d7-7ad6-4978-a5e8-bf64a40c0424.png)
![image](https://user-images.githubusercontent.com/25856057/180435840-fc8a4eb2-c41b-479e-a6d7-52290589962a.png)

**Comment by junke365** [comment]
The class cannot be reached,

**Comment by jaredjj3** [comment]
It's a static function, not a constructor. You cannot invoke `new` on it. Please look at https://github.com/stringsync/stringsync/blob/master/web/src/lib/MusicDisplay/locator/MusicDisplayLocator.ts and see what arguments it's supposed to take.

**Comment by junke365** [comment]
I don't know how to write TS, thank you very much

**Comment by junke365** [comment]
![image](https://user-images.githubusercontent.com/25856057/180436658-85511e05-9340-4885-9bb9-13b69a51ce78.png)

**Comment by junke365** [comment]
Oh, yeah? But it's still the same error

**Comment by jaredjj3** [comment]
Take a look at this [article about the `static` keyword](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/static)

**Comment by junke365** [comment]
![image](https://user-images.githubusercontent.com/25856057/180437109-9a5c387e-23bf-45cd-b1a3-5d7889d83098.png)

**Comment by junke365** [comment]
![image](https://user-images.githubusercontent.com/25856057/180437400-ae669c1e-4151-4eb2-8546-586ce6bb847b.png)

**Comment by junke365** [comment]
![image](https://user-images.githubusercontent.com/25856057/180438191-cc0c4100-4412-40d1-9c1b-aedb3c66d85e.png)

**Comment by junke365** [comment]
okay
